/* © 2026 Verdens Beste Musikkskole. Alle rettigheter forbeholdt. Verk-ID: VBM-K7Q4-CV9U. Signatur: bf337bfd3ba9686ea01e757a1996aa9c1cffd86425fb5f5115cfe4cf5e7d08e9 */
/* =====================================================================
   Verdens Beste Musikkskole – ORDBOK: Engelsk
   ---------------------------------------------------------------------
   Venstre side: teksten slik den står på siden. Høyre side: oversettelsen.
   «felles» gjelder alle sider. Under «sider» står tekst for én side.
   false betyr at teksten skjules på dette språket.
   Ny side: legg til en ny blokk under «sider» med filnavnet.
   ===================================================================== */
VBM_ORDBOK("en", {
  felles: {
    "Verdens Beste Musikkskole": "World's Best Music School",
    "Verdens Beste Musikklærer": "World's Best Music Teacher",
    "Originalen av denne siden finnes på ": "The original of this page is at ",
    "← Alle ressurser": "← All resources",
    "<a href=\"index.html\">← Alle ressurser</a>": "<a href=\"index.html\">← All resources</a>",
    "Nettsted": "Site",
    "Farger": "Color",
    "Svart-hvitt": "Black and white",
    "Farger eller svart-hvitt": "Color or black and white",
    "(Svart-hvitt) ": "(Black and white) ",
    "Piano": "Piano",
    "Gitar": "Guitar",
    "Strykere": "Strings",
    "Velg instrument": "Choose instrument",
    "spill": "play",
    "Noter": "Music notation",
    "Designet og levert av": "Designed and delivered by",
    "med liten hjelp av Claude AI": "with a little help from Claude AI",
    "september 2026": "September 2026",
    "Lyd: Salamander Grand Piano av Alexander Holm (CC BY 3.0). Gitar, fiolin og cello fra tonejs-instruments av Nicholas Brosowsky (CC BY 3.0).": "Sound: Salamander Grand Piano by Alexander Holm (CC BY 3.0). Guitar, violin and cello from tonejs-instruments by Nicholas Brosowsky (CC BY 3.0).",
    "Lyd: Salamander Grand Piano av Alexander Holm (CC BY 3.0).": "Sound: Salamander Grand Piano by Alexander Holm (CC BY 3.0).",
    "Intervallfarger (stolper og klammer)": "Interval colors (bars and brackets)",
    "ren prim": "unison",
    "Ren prim": "Unison",
    "Spill av Ren prim": "Play Unison",
    "liten sekund": "minor 2nd",
    "Liten sekund": "Minor 2nd",
    "Spill av Liten sekund": "Play Minor 2nd",
    "stor sekund": "major 2nd",
    "Stor sekund": "Major 2nd",
    "Spill av Stor sekund": "Play Major 2nd",
    "liten ters": "minor 3rd",
    "Liten ters": "Minor 3rd",
    "Spill av Liten ters": "Play Minor 3rd",
    "stor ters": "major 3rd",
    "Stor ters": "Major 3rd",
    "Spill av Stor ters": "Play Major 3rd",
    "ren kvart": "perfect 4th",
    "Ren kvart": "Perfect 4th",
    "Spill av Ren kvart": "Play Perfect 4th",
    "tritonus": "tritone",
    "Tritonus": "Tritone",
    "Spill av Tritonus": "Play Tritone",
    "ren kvint": "perfect 5th",
    "Ren kvint": "Perfect 5th",
    "Spill av Ren kvint": "Play Perfect 5th",
    "liten sekst": "minor 6th",
    "Liten sekst": "Minor 6th",
    "Spill av Liten sekst": "Play Minor 6th",
    "stor sekst": "major 6th",
    "Stor sekst": "Major 6th",
    "Spill av Stor sekst": "Play Major 6th",
    "liten septim": "minor 7th",
    "Liten septim": "Minor 7th",
    "Spill av Liten septim": "Play Minor 7th",
    "stor septim": "major 7th",
    "Stor septim": "Major 7th",
    "Spill av Stor septim": "Play Major 7th",
    "ren oktav": "perfect octave",
    "Ren oktav": "Perfect octave",
    "Spill av Ren oktav": "Play Perfect octave",
    "liten none": "minor 9th",
    "Liten none": "Minor 9th",
    "Spill av Liten none": "Play Minor 9th",
    "stor none": "major 9th",
    "Stor none": "Major 9th",
    "Spill av Stor none": "Play Major 9th",
    "liten decim": "minor 10th",
    "Liten decim": "Minor 10th",
    "Spill av Liten decim": "Play Minor 10th",
    "stor decim": "major 10th",
    "Stor decim": "Major 10th",
    "Spill av Stor decim": "Play Major 10th",
    "ren undecim": "perfect 11th",
    "Ren undecim": "Perfect 11th",
    "Spill av Ren undecim": "Play Perfect 11th",
    "forstørret undecim": "augmented 11th",
    "Forstørret undecim": "Augmented 11th",
    "Spill av Forstørret undecim": "Play Augmented 11th",
    "ren duodecim": "perfect 12th",
    "Ren duodecim": "Perfect 12th",
    "Spill av Ren duodecim": "Play Perfect 12th",
    "liten tredecim": "minor 13th",
    "Liten tredecim": "Minor 13th",
    "Spill av Liten tredecim": "Play Minor 13th",
    "stor tredecim": "major 13th",
    "Stor tredecim": "Major 13th",
    "Spill av Stor tredecim": "Play Major 13th",
    "liten kvartdecim": "minor 14th",
    "Liten kvartdecim": "Minor 14th",
    "Spill av Liten kvartdecim": "Play Minor 14th",
    "stor kvartdecim": "major 14th",
    "Stor kvartdecim": "Major 14th",
    "Spill av Stor kvartdecim": "Play Major 14th",
    "dobbel oktav": "double octave",
    "Dobbel oktav": "Double octave",
    "Spill av Dobbel oktav": "Play Double octave",
    "forminsket kvint": "diminished 5th",
    "Forminsket kvint": "Diminished 5th",
    "Spill av Forminsket kvint": "Play Diminished 5th",
    "forstørret kvint": "augmented 5th",
    "Forstørret kvint": "Augmented 5th",
    "Spill av Forstørret kvint": "Play Augmented 5th",
    "forstørret kvart": "augmented 4th",
    "Forstørret kvart": "Augmented 4th",
    "Spill av Forstørret kvart": "Play Augmented 4th",
    "forminsket septim": "diminished 7th",
    "Forminsket septim": "Diminished 7th",
    "Spill av Forminsket septim": "Play Diminished 7th",
    "forstørret sekst": "augmented 6th",
    "Forstørret sekst": "Augmented 6th",
    "Spill av Forstørret sekst": "Play Augmented 6th"
  },
  sider: {
    "index.html": {
        "Verdens Beste Musikkskole: juksebøker og lytteguider": "World's Best Music School: cheat books and listening guides",
        "Gratis ressurser i musikkteori og øretrening fra Verdens Beste Musikklærer.": "Free resources in music theory and ear training from World's Best Music Teacher.",
        "Juksebøker og lytteguider": "Cheat books and listening guides",
        "for musikkteori og øretrening": "for music theory and ear training",
        "Ekte notasjon, lyd og Spotify-lenker": "Real notation, sound and Spotify links",
        "Notelinje med g-nøkkel og noter": "Staff with treble clef and notes",
        "Slå på JavaScript i nettleseren for å se innholdet.": "Turn on JavaScript in your browser to see the content.",
        "Fant ikke materialer.js. Sjekk at filen ligger på GitHub ved siden av index.html.": "Could not find materialer.js. Check that the file is on GitHub next to index.html.",
        "Juksebøker": "Cheat books",
        "Bøker til <em>oppslag</em>": "Books for <em>reference</em>",
        "Oppslagsverk med ekte noter i C. Trykk på spill-knappen for å høre, på piano, gitar eller strykere.": "Reference books with real notation in C. Press the play button to listen, on piano, guitar or strings.",
        "Øretrening": "Ear training",
        "Hør og <em>lytt</em>": "Hear and <em>listen</em>",
        "Kjente sanger og verk som viser lyden av intervaller og akkorder.": "Well-known songs and pieces that show the sound of intervals and chords.",
        "Elevhefter": "Student workbooks",
        "Hefter til <em>timen</em>": "Workbooks for <em>class</em>",
        "Arbeidshefter til bruk i undervisningen.": "Workbooks for use in teaching.",
        "Nytt": "New",
        "Åpne": "Open",
        "Åpne i farger": "Open in color",
        "Åpne i svart-hvitt": "Open in black and white",
        "25 intervaller": "25 intervals",
        "Intervall-jukseboka": "The Interval Cheat Book",
        "Alle intervaller fra ren prim til dobbel oktav, med begge navn over oktaven.": "Every interval from unison to double octave, with both names above the octave.",
        "34 akkorder": "34 chords",
        "Den ultimate jukseboka for akkorder og intervaller": "The Ultimate Cheat Book for Chords and Intervals",
        "Fire kapitler, fra treklanger til 13-akkorder, kvartalakkorder og mer.": "Four chapters, from triads to 13th chords, quartal chords and more.",
        "Intervaller": "Intervals",
        "Intervaller & sanger": "Intervals & songs",
        "Hvert intervall oppover og nedover, med eksempelsanger og Spotify-lenker.": "Every interval up and down, with example songs and Spotify links.",
        "Lytteguide": "Listening guide",
        "Dominant- og majorakkorder med septim og none": "Dominant & Major 7th/9th Chords",
        "Septim- og nonakkorder hos Chopin, Debussy, Hendrix og James Brown.": "Seventh and ninth chords in Chopin, Debussy, Hendrix and James Brown.",
        "Mikrointervaller": "Microintervals",
        "Gehørlekser med mikrointervaller": "Ear training homework with microintervals",
        "Seks øvelser i små forskjeller i tonehøyde, som forberedelse til pianostemmerutdanningen ved NMH.": "Six exercises in small differences in pitch, as preparation for piano tuning studies.",
        "Treklanger": "Triads",
        "Akkordhefte": "Chord Workbook",
        "Treklanger, trinnakkorder og diatonisk harmoni, med harmonisk moll.": "Triads, scale-degree chords and diatonic harmony, with harmonic minor."
      },
    "intervaller.html": {
        "Intervall-jukseboka: fra prim til dobbel oktav": "The Interval Cheat Book: from unison to double octave",
        "Intervall-jukseboka": "The Interval Cheat Book",
        "Alle intervaller fra ren prim til dobbel oktav: to oktaver, 25 avstander i alt. Trykk på spill-knappen for å høre intervallet.": "Every interval from unison to double octave: two octaves, 25 distances in all. Press the play button to hear the interval.",
        "<strong>Om fargene:</strong> hver tone har sin farge fra Newtons regnbue, slik solresol bruker dem: C rød, D oransje, E gul, F grønn, G blå, A indigo og H fiolett. Spekteret er utvidet med nyanser: ♯ gir en lysere og ♭ en mørkere utgave av fargen. Intervallene får fargen til tonen de lander på fra C. En ters (C–E) er gul, en kvint (C–G) blå. På samme måte er liten variant mørkere enn stor, og over oktaven gjentas fargene.": "<strong>About the colors:</strong> each note has its color from Newton’s rainbow, the way Solresol uses them: C red, D orange, E yellow, F green, G blue, A indigo and B violet. The spectrum is extended with shades: ♯ gives a lighter and ♭ a darker version of the color. Each interval takes the color of the note it lands on from C. A third (C–E) is yellow, a fifth (C–G) blue. In the same way, the minor version is darker than the major, and above the octave the colors repeat.",
        "Enkle intervaller (0–12 halvtoner)": "Simple intervals (0–12 semitones)",
        "Sammensatte intervaller (13–24 halvtoner)": "Compound intervals (13–24 semitones)",
        "Samme tone spilt. Dette er utgangspunktet alle andre intervaller måles fra.": "The same note played twice. This is the starting point all other intervals are measured from.",
        "6 halvtoner: forstørret kvart eller forminsket kvint": "6 semitones: augmented 4th or diminished 5th",
        "Over oktaven har hvert intervall to navn: det latinske tallnavnet (none, decim, undecim osv.), som fortsetter å telle trinn oppover, og en enklere beskrivelse som «oktav + liten ters». Begge navnene står under hvert intervall, og begge er riktige.": "Above the octave, every interval has two names: the number name (9th, 10th, 11th and so on), which keeps counting steps upward, and a simpler description like “octave + minor 3rd”. Both names are shown under each interval, and both are correct.",
        "24 halvtoner, også kalt kvintdecim": "24 semitones, also called a 15th",
        "0 halvtoner": "0 semitones",
        "1 halvtone": "1 semitone",
        "2 halvtoner": "2 semitones",
        "3 halvtoner": "3 semitones",
        "4 halvtoner": "4 semitones",
        "5 halvtoner": "5 semitones",
        "6 halvtoner": "6 semitones",
        "7 halvtoner": "7 semitones",
        "8 halvtoner": "8 semitones",
        "9 halvtoner": "9 semitones",
        "10 halvtoner": "10 semitones",
        "11 halvtoner": "11 semitones",
        "12 halvtoner": "12 semitones",
        "13 halvtoner": "13 semitones",
        "14 halvtoner": "14 semitones",
        "15 halvtoner": "15 semitones",
        "16 halvtoner": "16 semitones",
        "17 halvtoner": "17 semitones",
        "18 halvtoner": "18 semitones",
        "19 halvtoner": "19 semitones",
        "20 halvtoner": "20 semitones",
        "21 halvtoner": "21 semitones",
        "22 halvtoner": "22 semitones",
        "23 halvtoner": "23 semitones",
        "24 halvtoner": "24 semitones",
        "Ren prim <span class=\"name-en\">(Unison)</span>": "Unison",
        "ren prim, 0 halvtoner": "unison, 0 semitones",
        "Liten sekund <span class=\"name-en\">(Minor 2nd)</span>": "Minor 2nd",
        "liten sekund, 1 halvtone": "minor 2nd, 1 semitone",
        "Stor sekund <span class=\"name-en\">(Major 2nd)</span>": "Major 2nd",
        "stor sekund, 2 halvtoner": "major 2nd, 2 semitones",
        "Liten ters <span class=\"name-en\">(Minor 3rd)</span>": "Minor 3rd",
        "liten ters, 3 halvtoner": "minor 3rd, 3 semitones",
        "Stor ters <span class=\"name-en\">(Major 3rd)</span>": "Major 3rd",
        "stor ters, 4 halvtoner": "major 3rd, 4 semitones",
        "Ren kvart <span class=\"name-en\">(Perfect 4th)</span>": "Perfect 4th",
        "ren kvart, 5 halvtoner": "perfect 4th, 5 semitones",
        "Tritonus <span class=\"name-en\">(Tritone)</span>": "Tritone",
        "tritonus, 6 halvtoner": "tritone, 6 semitones",
        "Ren kvint <span class=\"name-en\">(Perfect 5th)</span>": "Perfect 5th",
        "ren kvint, 7 halvtoner": "perfect 5th, 7 semitones",
        "Liten sekst <span class=\"name-en\">(Minor 6th)</span>": "Minor 6th",
        "liten sekst, 8 halvtoner": "minor 6th, 8 semitones",
        "Stor sekst <span class=\"name-en\">(Major 6th)</span>": "Major 6th",
        "stor sekst, 9 halvtoner": "major 6th, 9 semitones",
        "Liten septim <span class=\"name-en\">(Minor 7th)</span>": "Minor 7th",
        "liten septim, 10 halvtoner": "minor 7th, 10 semitones",
        "Stor septim <span class=\"name-en\">(Major 7th)</span>": "Major 7th",
        "stor septim, 11 halvtoner": "major 7th, 11 semitones",
        "Ren oktav <span class=\"name-en\">(Perfect octave)</span>": "Perfect octave",
        "ren oktav, 12 halvtoner": "perfect octave, 12 semitones",
        "Liten none <span class=\"name-en\">(Minor 9th)</span>": "Minor 9th",
        "liten none, 13 halvtoner": "minor 9th, 13 semitones",
        "Stor none <span class=\"name-en\">(Major 9th)</span>": "Major 9th",
        "stor none, 14 halvtoner": "major 9th, 14 semitones",
        "Liten decim <span class=\"name-en\">(Minor 10th)</span>": "Minor 10th",
        "liten decim, 15 halvtoner": "minor 10th, 15 semitones",
        "Stor decim <span class=\"name-en\">(Major 10th)</span>": "Major 10th",
        "stor decim, 16 halvtoner": "major 10th, 16 semitones",
        "Ren undecim <span class=\"name-en\">(Perfect 11th)</span>": "Perfect 11th",
        "ren undecim, 17 halvtoner": "perfect 11th, 17 semitones",
        "Forstørret undecim <span class=\"name-en\">(Augmented 11th)</span>": "Augmented 11th",
        "forstørret undecim, 18 halvtoner": "augmented 11th, 18 semitones",
        "Ren duodecim <span class=\"name-en\">(Perfect 12th)</span>": "Perfect 12th",
        "ren duodecim, 19 halvtoner": "perfect 12th, 19 semitones",
        "Liten tredecim <span class=\"name-en\">(Minor 13th)</span>": "Minor 13th",
        "liten tredecim, 20 halvtoner": "minor 13th, 20 semitones",
        "Stor tredecim <span class=\"name-en\">(Major 13th)</span>": "Major 13th",
        "stor tredecim, 21 halvtoner": "major 13th, 21 semitones",
        "Liten kvartdecim <span class=\"name-en\">(Minor 14th)</span>": "Minor 14th",
        "liten kvartdecim, 22 halvtoner": "minor 14th, 22 semitones",
        "Stor kvartdecim <span class=\"name-en\">(Major 14th)</span>": "Major 14th",
        "stor kvartdecim, 23 halvtoner": "major 14th, 23 semitones",
        "Dobbel oktav <span class=\"name-en\">(Double octave)</span>": "Double octave",
        "dobbel oktav, 24 halvtoner": "double octave, 24 semitones",
        "13 halvtoner, også kalt oktav + liten sekund": "13 semitones, also called octave + minor 2nd",
        "14 halvtoner, også kalt oktav + stor sekund": "14 semitones, also called octave + major 2nd",
        "15 halvtoner, også kalt oktav + liten ters": "15 semitones, also called octave + minor 3rd",
        "16 halvtoner, også kalt oktav + stor ters": "16 semitones, also called octave + major 3rd",
        "17 halvtoner, også kalt oktav + ren kvart": "17 semitones, also called octave + perfect 4th",
        "18 halvtoner, også kalt oktav + tritonus": "18 semitones, also called octave + tritone",
        "19 halvtoner, også kalt oktav + ren kvint": "19 semitones, also called octave + perfect 5th",
        "20 halvtoner, også kalt oktav + liten sekst": "20 semitones, also called octave + minor 6th",
        "21 halvtoner, også kalt oktav + stor sekst": "21 semitones, also called octave + major 6th",
        "22 halvtoner, også kalt oktav + liten septim": "22 semitones, also called octave + minor 7th",
        "23 halvtoner, også kalt oktav + stor septim": "23 semitones, also called octave + major 7th"
      },
    "akkorder-og-intervaller.html": {
        "Den ultimate jukseboka for akkorder og intervaller": "The Ultimate Cheat Book for Chords and Intervals",
        "Den ultimate jukseboka": "The Ultimate Cheat Book",
        "for akkorder og intervaller": "for chords and intervals",
        "34 akkorder i 4 kapitler, med ekte notasjon, linjaler og slektskap": "34 chords in 4 chapters, with real notation, rulers and relationships",
        "Verdens Beste Musikklærer, 2026": "World's Best Music Teacher, 2026",
        "Hver akkord under vises på tre måter: ekte notasjon i C, en halvtone-for-halvtone-linjal som viser nøyaktig hvordan hvert intervall måles, og (der det er relevant) de mindre akkordene som gjemmer seg inni den store. <span class=\"kun-farge\">Fargene følger Newtons fargespekter, utvidet med lysere nyanser for ♯ og mørkere nyanser for ♭. </span>Det engelske navnet står i parentes ved siden av hvert akkordnavn, så boka fungerer på begge språk.": "Every chord below is shown in three ways: real notation in C, a semitone-by-semitone ruler that shows exactly how each interval is measured, and (where relevant) the smaller chords hiding inside the big one. <span class=\"kun-farge\">The colors follow Newton’s color spectrum, extended with lighter shades for ♯ and darker shades for ♭. </span>",
        "<strong>Om tonenavn:</strong> boka bruker skandinavisk/tysk navnebruk: H er tonen engelsktalende kaller B (h-moll = B minor), mens B hos oss betyr B♭ (B-dur = B♭ major). Altså: engelsk B = norsk H, og engelsk B♭ = norsk B.": false,
        "<strong>Om fargene:</strong> hver tone har sin farge fra Newtons regnbue, slik solresol bruker dem: C rød, D oransje, E gul, F grønn, G blå, A indigo og H fiolett. Spekteret er utvidet med nyanser: ♯ gir en lysere og ♭ en mørkere utgave av fargen. Intervallene får fargen til tonen de lander på fra C. En ters (C–E) er gul, en kvint (C–G) blå. På samme måte er liten variant mørkere enn stor, og over oktaven gjentas fargene.": "<strong>About the colors:</strong> each note has its color from Newton’s rainbow, the way Solresol uses them: C red, D orange, E yellow, F green, G blue, A indigo and B violet. The spectrum is extended with shades: ♯ gives a lighter and ♭ a darker version of the color. Each interval takes the color of the note it lands on from C. A third (C–E) is yellow, a fifth (C–G) blue. In the same way, the minor version is darker than the major, and above the octave the colors repeat.",
        "Slik virker linjalen": "How the ruler works",
        "En halvtone er det minste trinnet i vestlig musikk: ett bånd på en gitar, én tangent over på et piano, svart eller hvit. Linjen under viser alle 12 halvtonene fra en grunntone opp til oktaven; de små prikkene markerer halvtonene mellom notene. Hver <span class=\"kun-farge\">fargede </span>stolpe lenger ned i boka er bygget på akkurat denne linjalen.": "A semitone is the smallest step in Western music: one fret on a guitar, one key over on a piano, black or white. The line below shows all 12 semitones from a root up to the octave; the small dots mark the semitones between the notes. Every <span class=\"kun-farge\">colored </span>bar further down in the book is built on exactly this ruler.",
        "Kapittel 1: Grunnleggende": "Chapter 1: Basics",
        "Treklanger": "Triads",
        "Den mest stabile og konsonante klangen i vestlig musikk. Svært mye musikk starter og slutter på en durtreklang. Byggesteinen alle andre akkorder i boka måles mot: stor ters nederst, liten ters oppå.": "The most stable and consonant sound in Western music. A great deal of music starts and ends on a major triad. The building block every other chord in the book is measured against: major 3rd at the bottom, minor 3rd on top.",
        "Samme oppskrift som duren, bare med tersene byttet om: liten ters nederst, stor ters oppå. Den ene halvtonen (E blir E♭) er hele grunnen til at den høres mørkere og mer melankolsk ut.": "The same recipe as the major, just with the thirds swapped: minor 3rd at the bottom, major 3rd on top. That single semitone (E becomes E♭) is the whole reason it sounds darker and more melancholy.",
        "To små terser stablet. Den forminskede kvinten (C–G♭) er et tritonus, samme avstand som en forstørret kvart, bare skrevet annerledes. De tre øverste tonene i C7 (E–G–B) er nettopp en forminsket treklang, så de to er nære slektninger.": "Two minor thirds stacked. The diminished 5th (C–G♭) is a tritone, the same distance as an augmented 4th, just spelled differently. The top three notes of C7 (E–G–B♭) are exactly a diminished triad, so the two are close relatives.",
        "To store terser stablet. Den forstørrede kvinten (G♯) klinger likt som en liten sekst (A♭). Akkorden er symmetrisk: C+, E+ og G♯+ består av de samme tre tangentene, så øret kan ikke høre hvilken tone som er grunntonen.": "Two major thirds stacked. The augmented 5th (G♯) sounds the same as a minor 6th (A♭). The chord is symmetrical: C+, E+ and G♯+ are made of the same three keys, so the ear cannot tell which note is the root.",
        "Sus-akkorder": "Sus chords",
        "«Sus» betyr suspensjon: en tone som «henger» i stedet for tersen. Her er tersen byttet ut med sekunden, som gir en åpen, svevende klang. Samme toner som Gsus4 (G–C–D), bare med C i bassen.": "“Sus” means suspension: a note that “hangs” in place of the third. Here the third is replaced by the 2nd, which gives an open, floating sound. The same notes as Gsus4 (G–C–D), just with C in the bass.",
        "Her er tersen byttet ut med kvarten. Kvarten vil naturlig ned til tersen. Spill Csus4 etterfulgt av C og lytt etter draget. Samme toner som Fsus2 (F–G–C), bare med C i bassen.": "Here the third is replaced by the 4th. The 4th naturally wants to fall to the third. Play Csus4 followed by C and listen for the pull. The same notes as Fsus2 (F–G–C), just with C in the bass.",
        "Grunnleggende sekst- og septimakkorder": "Basic sixth and seventh chords",
        "Samme fire toner som Am7 (A–C–E–G). Det er bassen som avgjør hvilket navn vi bruker. Mye brukt som avslutningsakkord i swing og tidlig jazz.": "The same four notes as Am7 (A–C–E–G). The bass decides which name we use. Widely used as a final chord in swing and early jazz.",
        "Den store septimen (H) ligger bare en halvtone under oktaven og gir en blank, drømmende klang uten draget dominantseptimen har. De tre øverste tonene (E–G–H) er en molltreklang, så Cmaj7 er C-dur og e-moll lagt oppå hverandre.": "The major 7th (B) sits just a semitone below the octave and gives a bright, dreamy sound without the pull of the dominant 7th. The top three notes (E–G–B) are a minor triad, so Cmaj7 is C major and E minor stacked on top of each other.",
        "Den viktigste akkorden i funksjonsharmonikk: tersen og den lille septimen (E–B) danner et tritonus som vil løses til tonika. Det er V-en i nesten enhver ii–V–I og grunnakkorden i blues.": "The most important chord in functional harmony: the third and the minor 7th (E–B♭) form a tritone that wants to resolve to the tonic. It is the V in almost every ii–V–I and the basic chord of the blues.",
        "Standard mollakkord i jazz og soul, og ii-en i en ii–V–I (Dm7 i C-dur). Samme toner som E♭6 (E♭–G–B–C), akkurat som C6 og Am7 deler toner. De tre øverste tonene (E♭–G–B) er en durtreklang.": "The standard minor chord in jazz and soul, and the ii in a ii–V–I (Dm7 in C major). The same notes as E♭6 (E♭–G–B♭–C), just as C6 and Am7 share notes. The top three notes (E♭–G–B♭) are a major triad.",
        "Kapittel 2: Pianostemmerens beste venner": "Chapter 2: The piano tuner’s best friends",
        "Kvart og kvint": "Fourth and fifth",
        "Kvarten, kvinten og oktaven er de reneste intervallene etter primen, og de viktigste verktøyene til en pianostemmer. Stemmeren lytter etter svevninger: en rolig pulsering i lyden når to toner nesten, men ikke helt, stemmer med hverandre. I likesvevende temperatur er kvinten stemt en hårsbredd for smal og kvarten en hårsbredd for bred (rundt 2 cent; en halvtone er 100 cent). Midt på pianoet gir det omtrent én svevning i sekundet, og den farten er det stemmeren teller.": "The 4th, the 5th and the octave are the purest intervals after the unison, and the most important tools of a piano tuner. The tuner listens for beats: a slow pulsing in the sound when two notes are almost, but not quite, in tune with each other. In equal temperament the 5th is tuned a hair too narrow and the 4th a hair too wide (about 2 cents; a semitone is 100 cents). In the middle of the piano that gives about one beat per second, and that speed is what the tuner counts.",
        "Fem halvtoner, og den enkleste byggeklossen i dette kapitlet. Snudd opp-ned blir kvarten en kvint (C–F blir F–C), så en bar kvart kan lett høres som en kvint sett fra den øverste tonen. I likesvevende temperatur er kvarten stemt litt bred.": "Five semitones, and the simplest building block in this chapter. Turned upside down, the 4th becomes a 5th (C–F becomes F–C), so a bare 4th can easily be heard as a 5th seen from the top note. In equal temperament the 4th is tuned slightly wide.",
        "Sju halvtoner, det reneste intervallet etter oktaven. Ingen ters, så verken dur eller moll; derfor den typiske power chord-klangen i rock og metal. I likesvevende temperatur er kvinten stemt litt smal.": "Seven semitones, the purest interval after the octave. No third, so neither major nor minor; that is why it has the typical power chord sound of rock and metal. In equal temperament the 5th is tuned slightly narrow.",
        "Stablet til en oktav": "Stacked to an octave",
        "En kvart nederst og en kvint oppå, til sammen nøyaktig en oktav (5 + 7 = 12 halvtoner). Egentlig en kvintakkord på F, med C i bassen. Dette er pianostemmerens oktavtest: når oktaven C–C stemmer, svever kvarten og kvinten nøyaktig like fort.": "A 4th at the bottom and a 5th on top, together exactly an octave (5 + 7 = 12 semitones). Really a fifth chord on F, with C in the bass. This is the piano tuner’s octave test: when the octave C–C is in tune, the 4th and the 5th beat at exactly the same speed.",
        "Samme to intervaller i motsatt rekkefølge: kvinten nederst, kvarten oppå, og det er fortsatt en oktav. Dette er det klassiske power chord-grepet på gitar (C–G–C). Når oktaven stemmer, svever kvarten på toppen dobbelt så fort som kvinten under. Det er enda en sjekk pianostemmere bruker.": "The same two intervals in the opposite order: the 5th at the bottom, the 4th on top, and it is still an octave. This is the classic power chord shape on guitar (C–G–C). When the octave is in tune, the 4th on top beats twice as fast as the 5th below. That is another check piano tuners use.",
        "Stablede kvarter og kvinter": "Stacked fourths and fifths",
        "To rene kvarter stablet (C–F–B). Samme toner som Fsus4 (F–B–C) og Bsus2 (B–C–F), bare med en annen tone i bassen. Samme prinsipp ligger bak Miles Davis’ «So What»-akkord, som har tre kvarter og en stor ters på toppen.": "Two perfect 4ths stacked (C–F–B♭). The same notes as Fsus4 (F–B♭–C) and B♭sus2 (B♭–C–F), just with a different note in the bass. The same principle is behind Miles Davis’ “So What” chord, which has three 4ths and a major 3rd on top.",
        "To rene kvinter stablet (C–G–D). Samme toner som Csus2 (C–D–G) og Gsus4 (G–C–D). Stokk om tonene til D–G–C, og du får to kvarter: kvintal og kvartal er to sider av samme sak, fordi kvart + kvint = oktav. Gir en åpen, terseløs klang i modal jazz og moderne klassisk musikk.": "Two perfect 5ths stacked (C–G–D). The same notes as Csus2 (C–D–G) and Gsus4 (G–C–D). Rearrange the notes to D–G–C and you get two 4ths: quintal and quartal are two sides of the same thing, because 4th + 5th = octave. Gives an open sound without thirds in modal jazz and modern classical music.",
        "Kapittel 3: Videregående": "Chapter 3: Advanced",
        "Flere sekstakkorder og tilføyde toner": "More sixth chords and added notes",
        "Seksten her er fortsatt en stor sekst. Det er ♭3 som gjør akkorden til moll, ikke seksten. Samme fire toner som Am7♭5 (A–C–E♭–G), bare med en annen tone i bassen.": "The 6th here is still a major 6th. It is the ♭3 that makes the chord minor, not the 6th. The same four notes as Am7♭5 (A–C–E♭–G), just with a different note in the bass.",
        "I motsetning til sus4 beholdes tersen: kvarten legges til, den erstatter ikke tersen. Tersen og kvarten ligger bare en halvtone fra hverandre (E–F), så klangen blir litt krydret.": "Unlike sus4, the third is kept: the 4th is added, it does not replace the third. The third and the 4th are only a semitone apart (E–F), so the sound gets a little spicy.",
        "I motsetning til sus2 beholdes tersen: sekunden legges til, den erstatter ikke tersen. Legges sekunden en oktav opp, kalles akkorden add9, og klangen blir mykere.": "Unlike sus2, the third is kept: the 2nd is added, it does not replace the third. If the 2nd is moved up an octave, the chord is called add9, and the sound becomes softer.",
        "Flere septimakkorder": "More seventh chords",
        "Brukes som ii-akkorden i moll (for eksempel Dm7♭5 i c-moll). «Halvforminsket» fordi kvinten er forminsket, men septimen bare liten. Samme toner som E♭m6 (E♭–G♭–B–C), og bare én tone unna en forminsket septimakkord: senk septimen (B) en halvtone til A, så er du der.": "Used as the ii chord in minor (for example Dm7♭5 in C minor). “Half-diminished” because the 5th is diminished, but the 7th is only minor. The same notes as E♭m6 (E♭–G♭–B♭–C), and just one note away from a diminished 7th chord: lower the 7th (B♭) a semitone to A, and you are there.",
        "Bare små terser, så oktaven deles i fire like deler. Den forminskede septimen (♭♭7) klinger likt som en stor sekst (A), men skrives som en septim for at terssystemet skal holde. Symmetrisk: Cdim7, E♭dim7, G♭dim7 og Adim7 er de samme fire tangentene. Høres også ut som A♭7♭9 uten grunntone.": "Only minor thirds, so the octave is divided into four equal parts. The diminished 7th (♭♭7) sounds the same as a major 6th (A), but is written as a 7th so that the system of thirds holds. Symmetrical: Cdim7, E♭dim7, G♭dim7 and Adim7 are the same four keys. Also sounds like A♭7♭9 without the root.",
        "Molltreklang med stor septim, en mystisk, spenningsfylt klang. Nær slektning av forstørret majorseptimakkord (kapittel 4): begge har stor septim som ytterramme og en forstørret treklang inni. Forskjellen er rekkefølgen. Her ligger den lille tersen nederst og den forstørrede treklangen oppå (C | E♭–G–H); der ligger den forstørrede treklangen nederst og den lille tersen på toppen (C–E–G♯ | H). Byggeklossene er de samme, bare i speilvendt rekkefølge (3 + 4 + 4 halvtoner mot 4 + 4 + 3), og derfor låter de så beslektet. Sluttakkorden i James Bond-temaet er en slik akkord med none lagt til, og den finnes også i mollklisjeen Cm – Cm(maj7) – Cm7 – Cm6.": "A minor triad with a major 7th, a mysterious, tense sound. A close relative of the augmented major 7th chord (chapter 4): both have a major 7th as the outer frame and an augmented triad inside. The difference is the order. Here the minor 3rd is at the bottom and the augmented triad on top (C | E♭–G–B); there the augmented triad is at the bottom and the minor 3rd on top (C–E–G♯ | B). The building blocks are the same, just in mirrored order (3 + 4 + 4 semitones against 4 + 4 + 3), and that is why they sound so related. The final chord of the James Bond theme is this kind of chord with a 9th added, and it is also found in the minor cliché Cm – Cm(maj7) – Cm7 – Cm6.",
        "Utvidede akkorder": "Extended chords",
        "Dominantseptimen med enda en ters (D) på toppen. Den er fyldigere og mer fargerik, og mye brukt i funk og gospel. Tar du bort grunntonen, står du igjen med Em7♭5 (E–G–B–D).": "The dominant 7th with one more third (D) on top. It is fuller and more colorful, and much used in funk and gospel. Take away the root, and you are left with Em7♭5 (E–G–B♭–D).",
        "En blank, luftig klang, mye brukt i bossa nova og filmmusikk når man vil ha noe rikere enn majorseptimen uten at det blir dissonant. Uten grunntonen blir det Em7 (E–G–H–D). Derfor er Em7 over C i bassen en vanlig måte å spille den på.": "A bright, airy sound, much used in bossa nova and film music when you want something richer than the major 7th without it becoming dissonant. Without the root it becomes Em7 (E–G–B–D). That is why Em7 over C in the bass is a common way to play it.",
        "Mollseptimens fyldigere søsken, med none lagt til for en mykere, mer sofistikert klang. Vanlig i jazzballader. Uten grunntonen blir det E♭maj7 (E♭–G–B–D).": "The fuller sibling of the minor 7th, with a 9th added for a softer, more sophisticated sound. Common in jazz ballads. Without the root it becomes E♭maj7 (E♭–G–B♭–D).",
        "I praksis utelates ofte tersen når undecimen (kvarten en oktav opp) er med, siden E og F skurrer mot hverandre. Derfor spilles den ofte som B/C: en B-durtreklang (B–D–F) over C i bassen. Her står hele stabelen, så du ser hvordan akkorden bygges opp.": "In practice the third is often left out when the 11th (the 4th an octave up) is included, since E and F clash with each other. That is why it is often played as B♭/C: a B♭ major triad (B♭–D–F) over C in the bass. Here the whole stack is shown, so you can see how the chord is built.",
        "Undecimen skurrer ikke mot den lille tersen slik den gjør mot den store, så denne akkorden brukes friere, og den er vanlig i modal jazz. Stabler du tonene i kvarter (C–F–B–E♭–G), får du nøyaktig «So What»-akkorden fra kapittel 2.": "The 11th does not clash with the minor 3rd the way it does with the major one, so this chord is used more freely, and it is common in modal jazz. Stack the notes in 4ths (C–F–B♭–E♭–G), and you get exactly the “So What” chord from chapter 2.",
        "Hele tersstabelen: alle sju tonene i skalaen (C miksolydisk) klinger samtidig. I praksis spilles sjelden alle. Pianister velger ofte et utvalg, gjerne 1, 3, ♭7 og 13 (C–E–B–A).": "The whole stack of thirds: all seven notes of the scale (C Mixolydian) sound at once. In practice they are rarely all played. Pianists often choose a selection, typically 1, 3, ♭7 and 13 (C–E–B♭–A).",
        "Kapittel 4: Eksepsjonell": "Chapter 4: Exceptional",
        "Kromatiske sekstakkorder (klassisk)": "Chromatic sixth chords (classical)",
        "Durtreklangen på senket 2. trinn (D♭–F–A♭), vist med tersen (F) i bassen. Det er denne vendingen som gir navnet «sekst». Går vanligvis videre til dominanten, G. Navnet knyttes til operakomponistene i Napoli på 1700-tallet.": "The major triad on the lowered 2nd degree (D♭–F–A♭), shown with the third (F) in the bass. It is this inversion that gives the name “sixth”. It usually moves on to the dominant, G. The name is linked to the opera composers of Naples in the 1700s.",
        "Bygget på senket 6. trinn (A♭ i C-dur). Klinger som A♭7 uten kvint, men F♯ skrives som hevet 4. trinn fordi den skal opp til G, mens A♭ går ned til G. De to løses utover mot dominanten.": "Built on the lowered 6th degree (A♭ in C major). Sounds like A♭7 without the 5th, but F♯ is written as a raised 4th degree because it goes up to G, while A♭ goes down to G. The two resolve outward to the dominant.",
        "Samme forstørrede sekst-ramme som den italienske, med 2. trinn (D) lagt til. Inneholder to tritonuser (A♭–D og C–F♯), som gir den skarpe heltoneklangen. Samme tangenter som D7♭5.": "The same augmented sixth frame as the Italian, with the 2nd degree (D) added. It contains two tritones (A♭–D and C–F♯), which give the sharp whole-tone sound. The same keys as D7♭5.",
        "Den italienske seksten med ♭3 (E♭) lagt til. Enharmonisk identisk med A♭7 (A♭–C–E♭–G♭): samme tangenter, ulik skrivemåte og funksjon: A♭7 vil ned en kvint til D♭, mens tysk sekst vil utover til G.": "The Italian sixth with ♭3 (E♭) added. Enharmonically identical to A♭7 (A♭–C–E♭–G♭): the same keys, different spelling and function: A♭7 wants to go down a 5th to D♭, while the German sixth wants to open outward to G.",
        "Forstørrede septimakkorder": "Augmented seventh chords",
        "En dominantseptim med hevet kvint (C7♯5), en alterert dominant som gir enda mer spenning før oppløsningen. Inneholder en forstørret treklang fra grunntonen, og alle fire tonene hører til heltoneskalaen.": "A dominant 7th with a raised 5th (C7♯5), an altered dominant that gives even more tension before the resolution. It contains an augmented triad from the root, and all four notes belong to the whole-tone scale.",
        "Forstørret treklang (C–E–G♯) med stor septim på toppen, ofte skrevet maj7♯5. De tre øverste tonene (E–G♯–H) er en durtreklang. Nær slektning av moll-major-septimakkorden (kapittel 3): samme stor-septim-ramme og samme forstørrede treklang inni, bare speilvendt (4 + 4 + 3 halvtoner mot 3 + 4 + 4). Svevende, uavklart klang i moderne jazz og filmmusikk.": "An augmented triad (C–E–G♯) with a major 7th on top, often written maj7♯5. The top three notes (E–G♯–B) are a major triad. A close relative of the minor major 7th chord (chapter 3): the same major 7th frame and the same augmented triad inside, just mirrored (4 + 4 + 3 semitones against 3 + 4 + 4). A floating, unresolved sound in modern jazz and film music.",
        "Durtreklang <span class=\"name-en\">(major triad)</span>": "Major triad",
        "Spill av Durtreklang": "Play Major triad",
        "durtreklang": "major triad",
        "Molltreklang <span class=\"name-en\">(minor triad)</span>": "Minor triad",
        "Spill av Molltreklang": "Play Minor triad",
        "molltreklang": "minor triad",
        "Forminsket treklang <span class=\"name-en\">(diminished)</span>": "Diminished triad",
        "Spill av Forminsket treklang": "Play Diminished triad",
        "forminsket treklang": "diminished triad",
        "Forstørret treklang <span class=\"name-en\">(augmented)</span>": "Augmented triad",
        "Spill av Forstørret treklang": "Play Augmented triad",
        "forstørret treklang": "augmented triad",
        "Sus2 <span class=\"name-en\">(sus2)</span>": "Sus2",
        "Spill av Sus2": "Play Sus2",
        "sus2": "sus2",
        "Sus4 <span class=\"name-en\">(sus4)</span>": "Sus4",
        "Spill av Sus4": "Play Sus4",
        "sus4": "sus4",
        "Sekstakkord, dur <span class=\"name-en\">(added 6th)</span>": "Major 6th chord (added 6th)",
        "Spill av Sekstakkord, dur": "Play Major 6th chord (added 6th)",
        "sekstakkord, dur": "major 6th chord (added 6th)",
        "Majorseptimakkord <span class=\"name-en\">(major 7th)</span>": "Major 7th chord",
        "Spill av Majorseptimakkord": "Play Major 7th chord",
        "majorseptimakkord": "major 7th chord",
        "Dominantseptimakkord <span class=\"name-en\">(dominant 7th)</span>": "Dominant 7th chord",
        "Spill av Dominantseptimakkord": "Play Dominant 7th chord",
        "dominantseptimakkord": "dominant 7th chord",
        "Mollseptimakkord <span class=\"name-en\">(minor 7th)</span>": "Minor 7th chord",
        "Spill av Mollseptimakkord": "Play Minor 7th chord",
        "mollseptimakkord": "minor 7th chord",
        "Kvart <span class=\"name-en\">(4th)</span>": "4th",
        "Spill av Kvart": "Play 4th",
        "kvart": "4th",
        "Kvint <span class=\"name-en\">(5th / power chord)</span>": "5th (power chord)",
        "Spill av Kvint": "Play 5th (power chord)",
        "kvint": "5th (power chord)",
        "Kvart + kvint <span class=\"name-en\">(4th + 5th)</span>": "4th + 5th",
        "Spill av Kvart + kvint": "Play 4th + 5th",
        "kvart + kvint": "4th + 5th",
        "Kvint + kvart <span class=\"name-en\">(5th + 4th)</span>": "5th + 4th",
        "Spill av Kvint + kvart": "Play 5th + 4th",
        "kvint + kvart": "5th + 4th",
        "Kvartalakkord (stablede kvarter) <span class=\"name-en\">(quartal)</span>": "Quartal chord (stacked 4ths)",
        "Spill av Kvartalakkord (stablede kvarter)": "Play Quartal chord (stacked 4ths)",
        "kvartalakkord (stablede kvarter)": "quartal chord (stacked 4ths)",
        "Kvintalakkord (stablede kvinter) <span class=\"name-en\">(quintal)</span>": "Quintal chord (stacked 5ths)",
        "Spill av Kvintalakkord (stablede kvinter)": "Play Quintal chord (stacked 5ths)",
        "kvintalakkord (stablede kvinter)": "quintal chord (stacked 5ths)",
        "Sekstakkord, moll <span class=\"name-en\">(minor 6th)</span>": "Minor 6th chord",
        "Spill av Sekstakkord, moll": "Play Minor 6th chord",
        "sekstakkord, moll": "minor 6th chord",
        "Tilføyd kvart <span class=\"name-en\">(added 4th)</span>": "Added 4th",
        "Spill av Tilføyd kvart": "Play Added 4th",
        "tilføyd kvart": "added 4th",
        "Tilføyd sekund <span class=\"name-en\">(added 2nd)</span>": "Added 2nd",
        "Spill av Tilføyd sekund": "Play Added 2nd",
        "tilføyd sekund": "added 2nd",
        "Halvforminsket septimakkord (m7♭5) <span class=\"name-en\">(half-diminished 7th)</span>": "Half-diminished 7th chord (m7♭5)",
        "Spill av Halvforminsket septimakkord (m7♭5)": "Play Half-diminished 7th chord (m7♭5)",
        "halvforminsket septimakkord (m7♭5)": "half-diminished 7th chord (m7♭5)",
        "Forminsket septimakkord <span class=\"name-en\">(diminished 7th)</span>": "Diminished 7th chord",
        "Spill av Forminsket septimakkord": "Play Diminished 7th chord",
        "forminsket septimakkord": "diminished 7th chord",
        "Moll-major-septimakkord <span class=\"name-en\">(minor major 7th)</span>": "Minor major 7th chord",
        "Spill av Moll-major-septimakkord": "Play Minor major 7th chord",
        "moll-major-septimakkord": "minor major 7th chord",
        "Dominant noneakkord <span class=\"name-en\">(dominant 9th)</span>": "Dominant 9th chord",
        "Spill av Dominant noneakkord": "Play Dominant 9th chord",
        "dominant noneakkord": "dominant 9th chord",
        "Major noneakkord <span class=\"name-en\">(major 9th)</span>": "Major 9th chord",
        "Spill av Major noneakkord": "Play Major 9th chord",
        "major noneakkord": "major 9th chord",
        "Moll noneakkord <span class=\"name-en\">(minor 9th)</span>": "Minor 9th chord",
        "Spill av Moll noneakkord": "Play Minor 9th chord",
        "moll noneakkord": "minor 9th chord",
        "Dominant undecimakkord <span class=\"name-en\">(dominant 11th)</span>": "Dominant 11th chord",
        "Spill av Dominant undecimakkord": "Play Dominant 11th chord",
        "dominant undecimakkord": "dominant 11th chord",
        "Moll undecimakkord <span class=\"name-en\">(minor 11th)</span>": "Minor 11th chord",
        "Spill av Moll undecimakkord": "Play Minor 11th chord",
        "moll undecimakkord": "minor 11th chord",
        "Dominant tredecimakkord <span class=\"name-en\">(dominant 13th)</span>": "Dominant 13th chord",
        "Spill av Dominant tredecimakkord": "Play Dominant 13th chord",
        "dominant tredecimakkord": "dominant 13th chord",
        "Napolitansk sekst <span class=\"name-en\">(Neapolitan 6th)</span>": "Neapolitan 6th",
        "Spill av Napolitansk sekst": "Play Neapolitan 6th",
        "napolitansk sekst": "neapolitan 6th",
        "Italiensk sekst <span class=\"name-en\">(Italian 6th)</span>": "Italian 6th",
        "Spill av Italiensk sekst": "Play Italian 6th",
        "italiensk sekst": "italian 6th",
        "Fransk sekst <span class=\"name-en\">(French 6th)</span>": "French 6th",
        "Spill av Fransk sekst": "Play French 6th",
        "fransk sekst": "french 6th",
        "Tysk sekst <span class=\"name-en\">(German 6th)</span>": "German 6th",
        "Spill av Tysk sekst": "Play German 6th",
        "tysk sekst": "german 6th",
        "Forstørret septimakkord <span class=\"name-en\">(augmented 7th)</span>": "Augmented 7th chord",
        "Spill av Forstørret septimakkord": "Play Augmented 7th chord",
        "forstørret septimakkord": "augmented 7th chord",
        "Forstørret majorseptimakkord <span class=\"name-en\">(augmented major 7th)</span>": "Augmented major 7th chord",
        "Spill av Forstørret majorseptimakkord": "Play Augmented major 7th chord",
        "forstørret majorseptimakkord": "augmented major 7th chord",
        "halvforminsket septimakkord": "half-diminished 7th chord",
        "stor ters, 4 halvtoner": "major 3rd, 4 semitones",
        "ren kvint, 7 halvtoner": "perfect 5th, 7 semitones",
        "ren oktav, 12 halvtoner": "perfect octave, 12 semitones"
      },
    "intervaller-og-sanger.html": {
        "Intervaller & sanger: øretreningsreferanse": "Intervals & songs: ear training reference",
        "Øretrening og intervaller": "Ear training and intervals",
        "Intervaller &amp; <em>sanger</em>": "Intervals &amp; <em>songs</em>",
        "116 velkjente sanger organisert etter musikalsk intervall, oppover og nedover, til bruk i øretreningen. Hver linje har en lenke til Spotify-søk.": "116 well-known songs organized by musical interval, up and down, for use in ear training. Each line has a link to a Spotify search.",
        "Velg oppover eller nedover, og trykk på et intervall hvis du vil se bare det. Hvert kort har noter, lyd og kjente sanger som hjelper deg å kjenne igjen intervallet. Oppover starter på midten C, nedover på C en oktav høyere. Trykk på spill for å høre intervallet.": "Choose up or down, and tap an interval if you want to see only that one. Each card has notation, sound and well-known songs that help you recognize the interval. Up starts on middle C, down on the C an octave higher. Press play to hear the interval.",
        "Oppover": "Up",
        "Nedover": "Down",
        "Alle": "All",
        "Bruk nettleserens «Søk på side» (⌘/Ctrl+F) for å finne en bestemt sang.": "Use the browser’s “Find on page” (⌘/Ctrl+F) to find a particular song.",
        "Jaws (temamusikk)": "Jaws (theme)",
        "Fader Jakob (Frère Jacques)": "Are You Sleeping (Frère Jacques)",
        "tradisjonell": "traditional",
        "tradisjonell, svensk": "traditional, Swedish",
        "tradisjonell, 1745": "traditional, 1745",
        "Silent Night (Glade jul)": "Silent Night",
        "Våren (fra Årstidene)": "Spring (from The Four Seasons)",
        "Bob Thiele og George David Weiss, 1967": "Bob Thiele and George David Weiss, 1967",
        "tekst: John Newton, 1773": "lyrics: John Newton, 1773",
        "tekst: Isaac Watts, 1719": "lyrics: Isaac Watts, 1719",
        "Maria (refreng)": "Maria (chorus)",
        "The Winner Takes It All (refreng)": "The Winner Takes It All (chorus)",
        "Take on Me (refreng)": "Take on Me (chorus)",
        "Man in the Mirror (refreng)": "Man in the Mirror (chorus)",
        "Lady Jane (refreng)": "Lady Jane (chorus)",
        "Vals i ciss-moll": "Waltz in C♯ minor",
        "Nocturne i Ess-dur": "Nocturne in E♭ major",
        "Morgenstemning (Peer Gynt)": "Morning Mood (Peer Gynt)",
        "Symfoni nr. 5": "Symphony No. 5",
        "Menuett i G-dur": "Minuet in G major",
        "Merk: Spotify-lenkene fører til søk på tittel/komponist, ikke bekreftede direktelenker til én bestemt innspilling. Klikk deg videre til riktig versjon i søkeresultatet.": "Note: the Spotify links lead to a search for title/composer, not confirmed direct links to one specific recording. Click through to the right version in the search results.",
        "0 halvtoner oppover": "0 semitones up",
        "0 halvtoner nedover": "0 semitones down",
        "1 halvtone oppover": "1 semitone up",
        "1 halvtone nedover": "1 semitone down",
        "2 halvtoner oppover": "2 semitones up",
        "2 halvtoner nedover": "2 semitones down",
        "3 halvtoner oppover": "3 semitones up",
        "3 halvtoner nedover": "3 semitones down",
        "4 halvtoner oppover": "4 semitones up",
        "4 halvtoner nedover": "4 semitones down",
        "5 halvtoner oppover": "5 semitones up",
        "5 halvtoner nedover": "5 semitones down",
        "6 halvtoner oppover": "6 semitones up",
        "6 halvtoner nedover": "6 semitones down",
        "7 halvtoner oppover": "7 semitones up",
        "7 halvtoner nedover": "7 semitones down",
        "8 halvtoner oppover": "8 semitones up",
        "8 halvtoner nedover": "8 semitones down",
        "9 halvtoner oppover": "9 semitones up",
        "9 halvtoner nedover": "9 semitones down",
        "10 halvtoner oppover": "10 semitones up",
        "10 halvtoner nedover": "10 semitones down",
        "11 halvtoner oppover": "11 semitones up",
        "11 halvtoner nedover": "11 semitones down",
        "12 halvtoner oppover": "12 semitones up",
        "12 halvtoner nedover": "12 semitones down",
        "Spill av Ren prim oppover": "Play unison up",
        "Spill av Ren prim nedover": "Play unison down",
        "Spill av Liten sekund oppover": "Play minor 2nd up",
        "Spill av Liten sekund nedover": "Play minor 2nd down",
        "Spill av Stor sekund oppover": "Play major 2nd up",
        "Spill av Stor sekund nedover": "Play major 2nd down",
        "Spill av Liten ters oppover": "Play minor 3rd up",
        "Spill av Liten ters nedover": "Play minor 3rd down",
        "Spill av Stor ters oppover": "Play major 3rd up",
        "Spill av Stor ters nedover": "Play major 3rd down",
        "Spill av Ren kvart oppover": "Play perfect 4th up",
        "Spill av Ren kvart nedover": "Play perfect 4th down",
        "Spill av Tritonus oppover": "Play tritone up",
        "Spill av Tritonus nedover": "Play tritone down",
        "Spill av Ren kvint oppover": "Play perfect 5th up",
        "Spill av Ren kvint nedover": "Play perfect 5th down",
        "Spill av Liten sekst oppover": "Play minor 6th up",
        "Spill av Liten sekst nedover": "Play minor 6th down",
        "Spill av Stor sekst oppover": "Play major 6th up",
        "Spill av Stor sekst nedover": "Play major 6th down",
        "Spill av Liten septim oppover": "Play minor 7th up",
        "Spill av Liten septim nedover": "Play minor 7th down",
        "Spill av Stor septim oppover": "Play major 7th up",
        "Spill av Stor septim nedover": "Play major 7th down",
        "Spill av Ren oktav oppover": "Play perfect octave up",
        "Spill av Ren oktav nedover": "Play perfect octave down"
      },
    "gehorlekser-mikrointervaller.html": {
        "Gehørlekser med mikrointervaller: forberedelse til pianostemmerutdanningen": "Ear training homework with microintervals: preparation for piano tuning studies",
        "Øretrening for pianostemmere": "Ear training for piano tuners",
        "Gehørlekser med <em>mikrointervaller</em>": "Ear training with <em>microintervals</em>",
        "Seks øvelser som trener øret på svært små forskjeller i tonehøyde, som forberedelse til opptaksprøven på pianostemmerutdanningen ved Norges musikkhøgskole. En cent er en hundredel av en halvtone.": "Six exercises that train the ear on very small differences in pitch, as preparation for piano tuning studies. A cent is one hundredth of a semitone.",
        "Velg sinustoner eller piano nederst til høyre. Bruk gjerne hodetelefoner.": "Choose sine tones or piano at the bottom right. Headphones are a good idea.",
        "Pianolyden kunne ikke lastes, så sinustoner brukes i stedet.": "The piano sound could not be loaded, so sine tones are used instead.",
        "Samlet resultat": "Overall result",
        "Din fremgang": "Your progress",
        "Målet er fem riktige svar på rad i hver øvelse. I øvelse 3 teller det som riktig når du stemmer innenfor 5 cent. I øvelse 5 må begge valgene være riktige. I øvelse 6 teller det også som riktig når du bare bommer med ett trinn, for eksempel 15 i stedet for 20 cent. Resultatet nullstilles når du laster siden på nytt.": "The goal is five correct answers in a row in each exercise. In exercise 3 it counts as correct when you tune within 5 cents. In exercise 5 both choices must be correct. In exercise 6 it also counts as correct when you miss by just one step, for example 15 instead of 20 cents. The result is reset when you reload the page.",
        "<strong>Perfekt!</strong>Du har klart fem riktige på rad i alle seks øvelsene. Du har et helt eksepsjonelt gehør for små forskjeller i tonehøyde.": "<strong>Perfect!</strong> You got five correct in a row in all six exercises. You have a truly exceptional ear for small differences in pitch.",
        "<strong>Perfekt!</strong> Fem riktige på rad i alle seks øvelsene. Du har et helt eksepsjonelt gehør for små forskjeller i tonehøyde.": "<strong>Perfect!</strong> Five correct in a row in all six exercises. You have a truly exceptional ear for small differences in pitch.",
        "Øvelse 1": "Exercise 1",
        "Øvelse 2": "Exercise 2",
        "Øvelse 3": "Exercise 3",
        "Øvelse 4": "Exercise 4",
        "Øvelse 5": "Exercise 5",
        "Øvelse 6": "Exercise 6",
        "Høyere eller lavere": "Higher or lower",
        "Hører du svevninger?": "Do you hear beats?",
        "Stem selv": "Tune it yourself",
        "Rent eller surt intervall": "Pure or out-of-tune interval",
        "Hvor mye høyere eller lavere?": "How much higher or lower?",
        "For lite eller for stort intervall?": "Interval too small or too large?",
        "Du hører to toner etter hverandre. Er den andre tonen høyere eller lavere enn den første? Forskjellen velges tilfeldig for hver oppgave, fra 50 ned til 5 cent, og står over spill-knappen.": "You hear two notes one after the other. Is the second note higher or lower than the first? The difference is chosen at random for each task, from 50 down to 5 cents, and is shown above the play button.",
        "Forskjell:": "Difference:",
        "Neste oppgave": "Next task",
        "Høyere": "Higher",
        "Lavere": "Lower",
        "To toner klinger samtidig. Enten er de helt like, eller så er den ene litt ustemt. Når tonene ikke er like, hører du at lyden bølger, som et sakte vibrato. Det kalles svevninger.": "Two notes sound at the same time. Either they are exactly the same, or one of them is slightly out of tune. When the notes are not the same, you hear the sound wave, like a slow vibrato. These are called beats.",
        "Ja, svevninger": "Yes, beats",
        "Nei, helt rent": "No, perfectly pure",
        "To toner klinger samtidig, og den ene er ustemt. Dra i glidebryteren mens du lytter. Svevningene blir langsommere jo nærmere du kommer, og forsvinner når tonene er helt like. Bruk knappene «Litt ned» og «Litt opp» til å finjustere. Slik stemmer man et kor av strenger på pianoet.": "Two notes sound at the same time, and one is out of tune. Drag the slider while you listen. The beats get slower the closer you get, and disappear when the notes are exactly the same. Use the “A little down” and “A little up” buttons to fine-tune. This is how a unison of strings on the piano is tuned.",
        "Litt ned": "A little down",
        "Litt opp": "A little up",
        "Ferdig, sjekk": "Done, check",
        "Ny oppgave": "New task",
        "Du hører en oktav, en kvint eller en kvart. Er intervallet rent (oktav 2:1, kvint 3:2, kvart 4:3), eller er det litt surt? Med piano hører du et surt intervall som svevninger. Med sinustoner er svevningene svake, så lytt etter om samklangen er rolig eller urolig.": "You hear an octave, a fifth or a fourth. Is the interval pure (octave 2:1, fifth 3:2, fourth 4:3), or is it slightly out of tune? With piano you hear an out-of-tune interval as beats. With sine tones the beats are weak, so listen for whether the sound is calm or restless.",
        "Rent": "Pure",
        "Surt": "Out of tune",
        "Du hører to toner etter hverandre, med en tilfeldig forskjell mellom 50 og 5 cent. Velg om den andre tonen er høyere eller lavere, og hvor mange cent forskjellen er. Svaret vises når du har valgt begge deler.": "You hear two notes one after the other, with a random difference between 50 and 5 cents. Choose whether the second note is higher or lower, and how many cents the difference is. The answer is shown when you have chosen both.",
        "Retning": "Direction",
        "Forskjell": "Difference",
        "Du hører et intervall, først den nederste tonen og så den øverste. Er intervallet riktig, for lite eller for stort? Er det feil, velger du også hvor mange cent. Riktig betyr likesvevende temperert, slik et piano er stemt. Svaret vises når du har valgt.": "You hear an interval, first the bottom note and then the top one. Is the interval correct, too small or too large? If it is wrong, you also choose how many cents. Correct means equal tempered, the way a piano is tuned. The answer is shown when you have chosen.",
        "Intervall:": "Interval:",
        "Intervallet er": "The interval is",
        "For lite": "Too small",
        "Riktig": "Correct",
        "For stort": "Too large",
        "Hvor mye": "How much",
        "Sinustoner": "Sine tones",
        "Velg lyd": "Choose sound",
        "Spill oppgaven": "Play the task",
        "Spill tonene": "Play the notes",
        "Stem den andre tonen": "Tune the second note",
        "Øvelse {n}: {navn}": "Exercise {n}: {navn}",
        "{r} av {t} riktige.": "{r} of {t} correct.",
        "Fullført": "Completed",
        "På rad: {r} av {t}": "In a row: {r} of {t}",
        "Totalt: {r} av {t} riktige": "Total: {r} of {t} correct",
        "Totalt: {r} av {t} riktige.": "Total: {r} of {t} correct.",
        "Fullførte øvelser: {r} av {t}.": "Exercises completed: {r} of {t}.",
        "Fem riktige på rad. Denne øvelsen er fullført!": "Five correct in a row. This exercise is complete!",
        "Tre riktige på rad. Bra jobbet!": "Three correct in a row. Well done!",
        "Ti riktige på rad. Imponerende!": "Ten correct in a row. Impressive!",
        "Totalt i alle øvelsene: {s}.": "Total across all exercises: {s}.",
        "{r} av {t} riktige": "{r} of {t} correct",
        "Ikke gi opp. Øret blir bedre for hver oppgave.": "Don’t give up. Your ear gets better with every task.",
        "Små forskjeller er vanskelige for alle. Prøv igjen!": "Small differences are hard for everyone. Try again!",
        "Hør gjerne en gang til før du går videre.": "Feel free to listen once more before you move on.",
        "Selv pianostemmere trenger mange års trening. Du er på vei!": "Even piano tuners need many years of training. You are on your way!",
        "Pust rolig, lytt godt, og prøv neste.": "Breathe calmly, listen closely, and try the next one.",
        "{n} cent": function(v){ return v.n + (String(v.n) === '1' ? ' cent' : ' cents'); },
        "Riktig.": "Correct.",
        "Feil.": "Wrong.",
        "Delvis riktig.": "Partly correct.",
        "Nesten riktig.": "Almost correct.",
        "Det gir ingen hørbare svevninger.": "That gives no audible beats.",
        "Det gir omtrent én svevning hvert {n}. sekund.": "That gives about one beat every {n} seconds.",
        "Det gir omtrent {n} svevninger i sekundet.": "That gives about {n} beats per second.",
        "Den andre tonen var {c} høyere.": "The second note was {c} higher.",
        "Den andre tonen var {c} lavere.": "The second note was {c} lower.",
        "Tonene var helt like, uten svevninger.": "The notes were exactly the same, with no beats.",
        "Tonene var {c} fra hverandre.": "The notes were {c} apart.",
        "Svært godt.": "Very good.",
        "Godt.": "Good.",
        "Nesten rent.": "Almost in tune.",
        "Ikke helt rent ennå.": "Not quite in tune yet.",
        "Du stemte helt rent.": "You tuned it perfectly.",
        "Du stemte {c} for høyt.": "You tuned {c} too high.",
        "Du stemte {c} for lavt.": "You tuned {c} too low.",
        "Oktav": "Octave",
        "Kvint": "Fifth",
        "Kvart": "Fourth",
        "{navn}, helt ren.": "{navn}, perfectly pure.",
        "{navn}, der den øverste tonen var {c} for høy.": "{navn}, where the top note was {c} too high.",
        "{navn}, der den øverste tonen var {c} for lav.": "{navn}, where the top note was {c} too low.",
        "Retningen var riktig, men forskjellen var {c}, ikke {d}.": "The direction was right, but the difference was {c}, not {d}.",
        "Forskjellen var riktig, men den andre tonen var høyere, ikke lavere.": "The difference was right, but the second note was higher, not lower.",
        "Forskjellen var riktig, men den andre tonen var lavere, ikke høyere.": "The difference was right, but the second note was lower, not higher.",
        "Intervallet var helt riktig.": "The interval was exactly right.",
        "Intervallet var {c} for stort.": "The interval was {c} too large.",
        "Intervallet var {c} for lite.": "The interval was {c} too small.",
        "Du svarte helt riktig, bare ett trinn unna.": "You answered exactly right, just one step away.",
        "Du svarte {c} for stort, bare ett trinn unna.": "You answered {c} too large, just one step away.",
        "Du svarte {c} for lite, bare ett trinn unna.": "You answered {c} too small, just one step away.",
        "Intervallet var for stort, men {c}, ikke {d}.": "The interval was too large, but by {c}, not {d}.",
        "Intervallet var for lite, men {c}, ikke {d}.": "The interval was too small, but by {c}, not {d}.",
        "Antall cent var riktig, men intervallet var for stort, ikke for lite.": "The number of cents was right, but the interval was too large, not too small.",
        "Antall cent var riktig, men intervallet var for lite, ikke for stort.": "The number of cents was right, but the interval was too small, not too large."
      },
    "akkordhefte.html": {
        "Akkordhefte: treklanger og diatonisk harmoni": "Chord Workbook: triads and diatonic harmony",
        "G-nøkkel": "Treble clef",
        "ARBEIDSHEFTE I MUSIKKTEORI": "MUSIC THEORY WORKBOOK",
        "Treklanger og<br>diatonisk harmoni": "Triads and<br>diatonic harmony",
        "Et hefte om durtreklanger, molltreklanger og hvordan de settes sammen til en tonalitet, for deg som forbereder deg til AP-nivå musikkteori.": "A workbook about major triads, minor triads and how they fit together into a key, for you who are preparing for AP-level music theory.",
        "Navn": "Name",
        "Dato": "Date",
        "Innhold": "Contents",
        "Byggeklossene: intervaller": "The building blocks: intervals",
        "De fire grunnleggende treklangene": "The four basic triads",
        "Øv deg: stav akkorder": "Practice: spell chords",
        "Romertallsanalyse i dur": "Roman numeral analysis in major",
        "Egentest": "Self-test",
        "Utvidelse: harmonisk moll": "Extension: harmonic minor",
        "Del 1": "Part 1",
        "Del 2": "Part 2",
        "Del 3": "Part 3",
        "Del 4": "Part 4",
        "Del 5": "Part 5",
        "Del 6: utvidelse": "Part 6: extension",
        "<span class=\"label\">Om tonenavn</span> Heftet bruker skandinavisk navnebruk: H er tonen engelsktalende kaller B, mens B hos oss betyr B♭. Altså: engelsk B = norsk H, og engelsk B♭ = norsk B.": false,
        "Før du kan bygge en akkord, må du kunne måle avstanden mellom to toner. Den minste avstanden i vestlig musikk er en <strong>halvtone</strong>. To halvtoner utgjør en <strong>heltone</strong>.": "Before you can build a chord, you need to be able to measure the distance between two notes. The smallest distance in Western music is a <strong>semitone</strong>. Two semitones make a <strong>whole tone</strong>.",
        "De to intervallene du trenger aller mest i dette heftet:": "The two intervals you need most in this workbook:",
        "<strong>Stor ters</strong>: 4 halvtoner (f.eks. C til E)<br> <strong>Liten ters</strong>: 3 halvtoner (f.eks. C til E♭)": "<strong>Major 3rd</strong>: 4 semitones (e.g. C to E)<br> <strong>Minor 3rd</strong>: 3 semitones (e.g. C to E♭)",
        "<span class=\"label\">Lytt først</span> Be noen spille en dur-treklang og en moll-treklang etter hverandre, eller spill dem selv. Legg merke til stemningen før du går videre. Dur og moll høres forskjellig ut lenge før du kan forklare hvorfor.": "<span class=\"label\">Listen first</span> Ask someone to play a major triad and a minor triad one after the other, or play them yourself. Notice the mood before you move on. Major and minor sound different long before you can explain why.",
        "Øvelse": "Exercise",
        "Finn en stor ters og en liten ters med utgangspunkt i C, på klaviatur eller ditt eget instrument. Skriv ned tonene du kom fram til:": "Find a major 3rd and a minor 3rd starting from C, on a keyboard or your own instrument. Write down the notes you found:",
        "Stor ters fra C:": "Major 3rd from C:",
        "Liten ters fra C:": "Minor 3rd from C:",
        "En treklang bygges i <strong>terser</strong>: du stabler toner oppå hverandre, som en snømann på notesystemet. Kombinasjonen av store og små terser avgjør hvilken av de fire kvalitetene du får.": "A triad is built in <strong>thirds</strong>: you stack notes on top of each other, like a snowman on the staff. The combination of major and minor thirds decides which of the four qualities you get.",
        "Dur": "Major",
        "Moll": "Minor",
        "Forminsket": "Diminished",
        "Forstørret": "Augmented",
        "Grunntone + stor ters + ren kvint": "Root + major 3rd + perfect 5th",
        "Grunntone + liten ters + ren kvint": "Root + minor 3rd + perfect 5th",
        "Grunntone + liten ters + forminsket kvint": "Root + minor 3rd + diminished 5th",
        "Grunntone + stor ters + forstørret kvint": "Root + major 3rd + augmented 5th",
        "Lys, stabil, glad": "Bright, stable, happy",
        "Mørk, alvorlig, trist": "Dark, serious, sad",
        "Anspent, uløst": "Tense, unresolved",
        "Drømmende, svevende": "Dreamy, floating",
        "<span class=\"label\">Se sammenhengen</span> Alle fire kvalitetene er bare ulike kombinasjoner av stor og liten ters stablet oppå hverandre. Forminsket og forstørret er ikke unntak. De følger samme logikk som dur og moll.": "<span class=\"label\">See the connection</span> All four qualities are just different combinations of major and minor thirds stacked on top of each other. Diminished and augmented are not exceptions. They follow the same logic as major and minor.",
        "Refleksjon": "Reflection",
        "Hvilken av de fire tror du høres oftest i popmusikk, og hvorfor?": "Which of the four do you think is heard most often in pop music, and why?",
        "Si tersene høyt for deg selv mens du skriver («stor ters, liten ters»). Det gjør at mønsteret sitter bedre.": "Say the thirds out loud to yourself while you write (“major 3rd, minor 3rd”). That helps the pattern stick.",
        "Øvelse 1": "Exercise 1",
        "Øvelse 2": "Exercise 2",
        "Øvelse 3: sjekkpunkt": "Exercise 3: checkpoint",
        "Stav en G-dur-treklang:": "Spell a G major triad:",
        "Gjør den om til G-moll:": "Change it to G minor:",
        "G-dur: G – H – D<br>G-moll: G – B – D": "G major: G – B – D<br>G minor: G – B♭ – D",
        "Stav en D-moll-treklang:": "Spell a D minor triad:",
        "Gjør den om til D-forminsket:": "Change it to D diminished:",
        "D-moll: D – F – A<br>D-forminsket: D – F – A♭": "D minor: D – F – A<br>D diminished: D – F – A♭",
        "Stav en E-dur-treklang:": "Spell an E major triad:",
        "Gjør den om til E-forstørret:": "Change it to E augmented:",
        "E-dur: E – G♯ – H<br>E-forstørret: E – G♯ – H♯ (=C)": "E major: E – G♯ – B<br>E augmented: E – G♯ – B♯ (=C)",
        "<span class=\"label\">Stopp og sjekk</span> Kan du forklare med egne ord hvorfor en forminsket treklang er «mindre» enn en molltreklang? Hvis ikke, bla tilbake til Del 2 og se på terskombinasjonene på nytt før du fortsetter.": "<span class=\"label\">Stop and check</span> Can you explain in your own words why a diminished triad is “smaller” than a minor triad? If not, go back to Part 2 and look at the combinations of thirds again before you continue.",
        "Når en akkord tilhører en skala, merker vi den med romertall etter hvilket trinn den er bygget på. Dette kalles diatonisk harmoni. Under ser du C-dur-skalaen som eksempel.": "When a chord belongs to a scale, we label it with a Roman numeral for the degree it is built on. This is called diatonic harmony. Below you see the C major scale as an example.",
        "Diatoniske treklanger i C-dur": "Diatonic triads in C major",
        "Trinn": "Degree",
        "Romertall": "Roman numeral",
        "Kvalitet": "Quality",
        "Akkord": "Chord",
        "dur": "major",
        "moll": "minor",
        "forminsket": "diminished",
        "forstørret": "augmented",
        "E – G – H": "E – G – B",
        "G – H – D": "G – B – D",
        "H – D – F": "B – D – F",
        "E – G♯ – H": "E – G♯ – B",
        "G♯ – H – D": "G♯ – B – D",
        "<strong>Huskeregel:</strong> Stor bokstav = dur. Liten bokstav = moll. Liten bokstav med sirkel (°) = forminsket.": "<strong>Rule of thumb:</strong> Capital letter = major. Small letter = minor. Small letter with a circle (°) = diminished.",
        "<span class=\"label\">Hvor ble det av «aug»?</span> Legg merke til at forstørret treklang ikke finnes i denne tabellen. Forstørrede treklanger oppstår ikke naturlig i en vanlig dur-skala. De dukker først opp i harmonisk moll. Mer om det i Del 6.": "<span class=\"label\">Where did “aug” go?</span> Notice that the augmented triad is not in this table. Augmented triads do not occur naturally in an ordinary major scale. They first appear in harmonic minor. More about that in Part 6.",
        "Finn mønsteret": "Find the pattern",
        "Hvilke tre trinn i C-dur er dur-akkorder?": "Which three degrees in C major are major chords?",
        "Hvilke tre trinn er moll-akkorder?": "Which three degrees are minor chords?",
        "Svar på spørsmålene under uten å bla tilbake. Sjekk deg selv med fasiten når du er ferdig.": "Answer the questions below without looking back. Check yourself with the answers when you are done.",
        "1. Hvilke to intervaller utgjør en dur-treklang?": "1. Which two intervals make up a major triad?",
        "2. Hvilken akkordkvalitet er bygget på 7. trinn i en dur-skala?": "2. Which chord quality is built on the 7th degree of a major scale?",
        "3. Stav en F-moll-treklang.": "3. Spell an F minor triad.",
        "4. Hvorfor finnes det ingen forstørret treklang blant de diatoniske akkordene i en dur-skala?": "4. Why is there no augmented triad among the diatonic chords of a major scale?",
        "5. Utfordring: bygg akkordene I–vii° i D-dur (bruk F♯ og C♯ der det trengs).": "5. Challenge: build the chords I–vii° in D major (use F♯ and C♯ where needed).",
        "1. Stor ters + liten ters (stablet fra grunntonen: grunntone – stor ters – ren kvint)<br> 2. Forminsket (vii°)<br> 3. F-moll: F – A♭ – C<br> 4. Fordi forstørrede treklanger ikke oppstår diatonisk i en vanlig dur-skala. De krever et hevet 7. trinn, som først finnes i harmonisk moll<br> 5. I: D–F♯–A, ii: E–G–H, iii: F♯–A–C♯, IV: G–H–D, V: A–C♯–E, vi: H–D–F♯, vii°: C♯–E–G": "1. Major 3rd + minor 3rd (stacked from the root: root – major 3rd – perfect 5th)<br> 2. Diminished (vii°)<br> 3. F minor: F – A♭ – C<br> 4. Because augmented triads do not occur diatonically in an ordinary major scale. They need a raised 7th degree, which is first found in harmonic minor<br> 5. I: D–F♯–A, ii: E–G–B, iii: F♯–A–C♯, IV: G–B–D, V: A–C♯–E, vi: B–D–F♯, vii°: C♯–E–G",
        "Harmonisk moll": "Harmonic minor",
        "Harmonisk moll er en naturlig mollskala med <strong>hevet 7. trinn</strong>. I A harmonisk moll blir G til G♯:": "Harmonic minor is a natural minor scale with a <strong>raised 7th degree</strong>. In A harmonic minor, G becomes G♯:",
        "A – H – C – D – E – F – <strong style=\"color:var(--burgundy)\">G♯</strong> – A": "A – B – C – D – E – F – <strong style=\"color:var(--burgundy)\">G♯</strong> – A",
        "Diatoniske treklanger i A harmonisk moll": "Diatonic triads in A harmonic minor",
        "Det hevede 7. trinnet gjør to viktige ting: det skaper en forstørret treklang på <strong>III</strong> (den ene diatoniske plassen forstørrede treklanger faktisk finnes), og det gjør at <strong>v blir V</strong> (moll blir dur), som skaper en ledetone med sterkt drag mot grunntonen.": "The raised 7th degree does two important things: it creates an augmented triad on <strong>III</strong> (the one diatonic place where augmented triads actually occur), and it makes <strong>v become V</strong> (minor becomes major), which creates a leading tone with a strong pull toward the tonic.",
        "<span class=\"label\">Lytt til forskjellen</span> Sammenlign V i naturlig moll (E–G–H, moll) med V i harmonisk moll (E–G♯–H, dur). Draget mot tonika er lett å høre. Det er derfor komponister bruker harmonisk moll.": "<span class=\"label\">Listen to the difference</span> Compare V in natural minor (E–G–B, minor) with V in harmonic minor (E–G♯–B, major). The pull toward the tonic is easy to hear. That is why composers use harmonic minor."
      }
  }
});
